### ISSUE TITLE
Only compatible VS 2015 & C# 6

### ISSUE THREAD

**Issue by LeMoussel** [mnta/Abot.MultiProxyPoliteWebCrawler#1]
It's not possible to compile with VS 2013 and C # 4.5.
Error on with this expression
* `nameof(...)` => some equivalent for C# before C# 6 in this post "[nameof expression in .net framework 4](http://stackoverflow.com/questions/31261955/nameof-expression-in-net-framework-4)"
* `ProxyQueueTimeoutMs => ((MultiProxyCrawlConfiguration) _config).ProxyQueueTimeoutMs` => I  found nothing on how to write a similar method in older versions like .net framework 4.

**Comment by mnta** [comment]
For .Net 4

nameof(...) can be replace by parameter name in string
ProxyQueueTimeoutMs => ... can be replace by ProxyQueueTimeoutMs { get { return ((MultiProxyCrawlConfiguration) _config).ProxyQueueTimeoutMs; } }
